### ISSUE TITLE
Более информативные сообщения при отсутствии результатов поиска

### ISSUE THREAD

**Issue by ruspl-afed** [AParovyshnaya/uchislov#80]
Результаты поиска должны содержать параметры запроса, чтобы было понятно, что поиск действительно произошел.

Например: `Ничего не найдено на букву "п" для 5-го класса`

**Comment by AParovyshnaya** [comment]
Попробую изменить поиск на более удобный

**Comment by AParovyshnaya** [comment]
Я тут подумала, что надо бы сделать issue другой
